### ISSUE TITLE
Assassin Bee Crashed Server

### ISSUE THREAD

**Issue by leojaxx** [rwtema/Careerbees#23]
When I put the Assassin Queen into the apiary with 3 chocolate frames the server crashed instantly. Not my server so I don't have the crash log, sorry.

**Comment by KingDan27** [comment]
not sure but a similar issue happened on my server today heres the crash log to hopefully provide more info on this crash. https://pastebin.com/cqbE3dwB

seemed to only happen when we speed this bees production up. testes in single player with no production increases and be worked fine

**Comment by tlitookilakin** [comment]
Same thing happened to me. the issue seems to be this:
`net.bdew.gendustry.machines.mproducer.TileMutagenProducer cannot be cast to forestry.api.apiculture.IBeeHousing
	at com.rwtema.careerbees.effects.EffectAssassin.performPosEffect(EffectAssassin.java:47)
	at com.rwtema.careerbees.effects.EffectWorldInteraction.performEffect(EffectWorldInteraction.java:46)`
It also crashed trying to do the same thing to Thermal Expansion machines.

Looking through the source, the issue seems to be this line:
`IBeeHousing house = (IBeeHousing) world.getTileEntity(blockPos);`
It seems to be performing this on all tileEntitys regardless of whether they are actually bee houses.
Wrapping the whole thing in `if (world.getTileEntity(blockPos) instanceof IBeeHousing) {...}` should fix it but that may not be the most efficient method.

**Comment by angelnc1989** [comment]
Have one too
https://pastebin.com/X21wEyby

**Comment by jmcaffee** [comment]
Seeing the same issue, non apiary blocks being cast to BeeHousings. Happened right after I finished breeding assassin bees.

Any idea of a work around to get the world to stop crashing till this is fixed?

**Comment by tlitookilakin** [comment]
Here's what I, personally, have been doing-
either not placing any TEs within the apiary's range (annoying, not recommended.) or
using them with a Bee Bee Gun, which does not have the crashing issue. I recommend doing this- although it does require honey, using an assassin princess/queen allows infinite usage. (and since Assassin bees don't breed into anything, I can't imagine you want them for anything other than their effect.) If you want to automate it you'll need an item user of some fashion, but eh. manual usage is not too bad.
