### ISSUE TITLE
Request: Fix for Assassin Bee

### ISSUE THREAD

**Issue by DarkDon** [rwtema/Careerbees#37]
Error: Assassin Bee crashed the server

Can be reproduced: yes, just put a assassin bee in a apiary and around it other apiarys

Would be great if you could push a update for careerbees or a fix at least... or is this mod dead?

**Comment by DarkDon** [comment]
Crash Report btw

[crash-2019-11-19_02.47.36-server.txt](https://github.com/rwtema/Careerbees/files/3861554/crash-2019-11-19_02.47.36-server.txt)

**Comment by ReiDaTecnologia** [comment]
Tbh with you i'm subscribed to this repo for more than a year and your issue is the first notification i had...
So i think i can say this mod is dead...
Just use the other bees like the op energy bee, ignore totally this damn glitched bee.

**Comment by mjevans** [comment]
I too encountered this in Crack Pack 3  https://github.com/DarkPacks/Crackpack-3/issues/113

Server crash when Assassin Bees (Career Bees) trigger in industrial apiary (was night on install, crashed literally right after I used a sleeping bag to make it day).

I had to reproduce this in single player, and thankfully my little test setup had additional blocks that I wouldn't have thought are related.

The fridge in question is on the other side of a wall, and I was using it to store bees since I thought it was cool to render them when I opened the door.  I hadn't realized this bee tried to kill things in _any_ inventory, not just apiaries (things that can produce byproducts).  Career Bees should catch that exception and abort processing that block.

```
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassCastException: net.blay09.mods.cookingforblockheads.tile.TileFridge cannot be cast to forestry.api.apiculture.IBeeHousing
	at com.rwtema.careerbees.effects.EffectAssassin.performPosEffect(EffectAssassin.java:47) ~[EffectAssassin.class:?]
	at com.rwtema.careerbees.effects.EffectWorldInteraction.performEffect(EffectWorldInteraction.java:46) ~[EffectWorldInteraction.class:?]
	at com.rwtema.careerbees.effects.EffectBaseThrottled.doEffectBase(EffectBaseThrottled.java:84) ~[EffectBaseThrottled.class:?]
	at com.rwtema.careerbees.effects.EffectBase.doEffect(EffectBase.java:167) ~[EffectBase.class:?]
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:187) ~[Bee.class:?]
	at forestry.apiculture.genetics.Bee.doEffect(Bee.java:168) ~[Bee.class:?]
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:276) ~[BeekeepingLogic.class:?]
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:253) ~[BeekeepingLogic.class:?]
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TileApiary.scala:137) ~[TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.class:?]
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129) ~[TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.class:?]
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TileApiary.scala:129) ~[TileApiary$$anonfun$2$$anonfun$apply$mcV$sp$1.class:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) ~[scala-library-2.11.1.jar:?]
	at net.bdew.gendustry.misc.DataSlotErrorStates.withSuspendedUpdates(DataSlotErrorStates.scala:80) ~[DataSlotErrorStates.class:?]
	at net.bdew.gendustry.machines.apiary.TileApiary$$anonfun$2.apply$mcV$sp(TileApiary.scala:129) ~[TileApiary$$anonfun$2.class:?]
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0$$anonfun$trigger$1.class:?]
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0$$anonfun$trigger$1.class:?]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:?]
	at net.bdew.lib.Event0.trigger(Event.scala:19) ~[Event0.class:?]
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24) ~[TileTicking$class.class:?]
	at net.bdew.gendustry.machines.apiary.TileApiary.func_73660_a(TileApiary.scala:44) ~[TileApiary.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
```

**Comment by mjevans** [comment]
It looks like (currently) line 34 was already trying to guard against this outcome... https://github.com/mjevans/Careerbees/blob/master/src/main/java/com/rwtema/careerbees/effects/EffectAssassin.java#L34

Looking at this I only have wild guesses about where Java might be going wrong.

https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/apiculture/IBeeHousing.java#L19

As someone that rarely touches Java code seeing an issue that looks like it shouldn't exist, it might be better for a developer that is up to date on Java quirks to take a look at this.

**Comment by sam-kirby** [comment]
https://github.com/DarkPacks/Crackpack-3/issues/113#issuecomment-565240884

**Comment by IMarvinTPA** [comment]
@rwtema Bump

**Comment by IMarvinTPA** [comment]
@rwtema Would you be open to this mod being forked?

**Comment by lex1975** [comment]
> It looks like (currently) line 34 was already trying to guard against this outcome... https://github.com/mjevans/Careerbees/blob/master/src/main/java/com/rwtema/careerbees/effects/EffectAssassin.java#L34
> 
> Looking at this I only have wild guesses about where Java might be going wrong.
> 
> https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/apiculture/IBeeHousing.java#L19
> 
> As someone that rarely touches Java code seeing an issue that looks like it shouldn't exist, it might be better for a developer that is up to date on Java quirks to take a look at this.

Your code is not compiled. Links in build.gradle is not working. Please upload the finished mod.
