### ISSUE TITLE
Server crash when right-clicking on an Apiary chest with a Bee Gun in hand

### ISSUE THREAD

**Issue by riskable** [rwtema/Careerbees#7]
I had the Bee Gun in hand with a Police Princess in the top slot and no other bees in the gun.  It was full of honey.  I right-clicked on an Apiary chest and the server crashed with the following:

    java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
        at com.rwtema.careerbees.entity.EntityBeeSwarm.func_70071_h_(EntityBeeSwarm.java:338)
        at net.minecraft.world.World.func_72866_a(World.java:1990)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
        at net.minecraft.world.World.func_72870_g(World.java:1952)
        at net.minecraft.world.World.func_72939_s(World.java:1756)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

Now the server won't come back up 😢 Here's the crash report (this is FTB Revelation 1.4.0)

[crash-2018-01-31_14.24.25-server.txt](https://github.com/rwtema/Careerbees/files/1682844/crash-2018-01-31_14.24.25-server.txt)

Let me know if you need any more details.  I was wearing a full suit of "armored" bee armor while this happened too (probably doesn't matter).

**Comment by riskable** [comment]
Awesome.
